# Generated by Django 2.2.10 on 2024-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YtVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=300)),
                ('titles', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=10000)),
                ('publishersDate', models.DateTimeField()),
                ('thumbnails', models.URLField()),
                ('chnl_id', models.CharField(max_length=300)),
                ('chnl_title', models.CharField(max_length=500)),
            ],
        ),
    ]
